# Generated by Django 6.0.6 on 2026-06-30 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0002_rename_bays_datacenterhack_bay'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacenterhack',
            name='name',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Bay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('watts', models.CharField(choices=[('1KW', 'Very Low (1KW)'), ('2KW', 'Low (2KW)'), ('4KW', 'Medium (4KW)'), ('8KW', 'HIGH (8KW)'), ('16KW', 'HIGH (16KW)')], default='2KW', max_length=10)),
                ('data_center_hack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bays', to='datacenter.datacenterhack')),
            ],
        ),
    ]
