# Generated by Django 6.0.6 on 2026-10-06 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model', '0011_delete_iainstallationtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='IaInstallationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ai_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_tasks', to='model.aiinstance')),
            ],
        ),
    ]
