# Generated by Django 6.0.6 on 2026-10-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iainstallationtask',
            name='time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
