# Generated by Django 6.0.6 on 2026-07-17 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300)),
                ('model', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('watts', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.brand')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.hardware')),
                ('cores', models.IntegerField()),
                ('threads', models.IntegerField()),
                ('ghz', models.FloatField()),
                ('score_bottleneck', models.IntegerField()),
            ],
            bases=('hardware.hardware',),
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.hardware')),
                ('score_bottleneck', models.IntegerField()),
                ('vram', models.IntegerField()),
                ('mhz', models.FloatField()),
            ],
            bases=('hardware.hardware',),
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.hardware')),
                ('gb', models.IntegerField()),
                ('mhz', models.IntegerField()),
            ],
            bases=('hardware.hardware',),
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.hardware')),
                ('gb', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
            bases=('hardware.hardware',),
        ),
    ]
