# Generated by Django 6.0.6 on 2026-08-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='rarity',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
