# Generated by Django 6.0.6 on 2026-08-26 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_hardware_rarity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='ghz',
            new_name='cpu_ghz',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='score_bottleneck',
            new_name='cpu_score_bottleneck',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='mhz',
            new_name='gpu_mhz',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='score_bottleneck',
            new_name='gpu_score_bottleneck',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='gb',
            new_name='ram_gb',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='mhz',
            new_name='ram_mhz',
        ),
        migrations.RenameField(
            model_name='ssd',
            old_name='gb',
            new_name='ssd_gb',
        ),
    ]
