# Generated by Django 6.0.6 on 2026-07-09 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_cpu_is_active_gpu_is_active_ram_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='price',
            new_name='cores',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='watts',
            new_name='threads',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='price',
            new_name='vram',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='price',
            new_name='gb',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='watts',
            new_name='mhz',
        ),
        migrations.RenameField(
            model_name='ssd',
            old_name='price',
            new_name='gb',
        ),
        migrations.RenameField(
            model_name='ssd',
            old_name='watts',
            new_name='speed',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='model',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='type',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='model',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='type',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='watts',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='model',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='type',
        ),
        migrations.RemoveField(
            model_name='ssd',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='ssd',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ssd',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ssd',
            name='model',
        ),
        migrations.RemoveField(
            model_name='ssd',
            name='type',
        ),
        migrations.AddField(
            model_name='cpu',
            name='ghz',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpu',
            name='mhz',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=300)),
                ('model', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('watts', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.brand')),
            ],
        ),
        migrations.AddField(
            model_name='cpu',
            name='hardware_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.hardware'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpu',
            name='hardware_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.hardware'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ram',
            name='hardware_ptr',
            field=models.OneToOneField(auto_created=True, default=2, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.hardware'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ssd',
            name='hardware_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hardware.hardware'),
            preserve_default=False,
        ),
    ]
