# Generated by Django 6.0.6 on 2026-08-27 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_rename_ghz_cpu_cpu_ghz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware',
            name='is_active',
        ),
    ]
