# Generated by Django 6.0.6 on 2026-09-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('gpu_vram', models.IntegerField()),
                ('ram_gb', models.IntegerField()),
                ('storage_gb', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('params', models.IntegerField()),
            ],
        ),
    ]
