# Generated by Django 6.0.6 on 2026-09-05 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='aimodel',
            name='mark_model',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='ai_models', to='model.markmodel'),
            preserve_default=False,
        ),
    ]
