# Generated by Django 6.0.6 on 2026-09-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_alter_aimodel_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='serie',
        ),
    ]
