# Generated by Django 6.0.6 on 2026-09-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_markmodel_aimodel_mark_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='params',
            field=models.BigIntegerField(),
        ),
    ]
