# Generated by Django 6.0.6 on 2026-09-14 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_remove_aimodel_serie'),
        ('server', '0005_alter_bay_cpu_alter_bay_gpu1_alter_bay_gpu2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField()),
                ('bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_instances', to='server.bay')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='model.aimodel')),
            ],
        ),
    ]
