# Generated by Django 6.0.6 on 2026-09-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_alter_aimodel_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
