# Generated by Django 6.0.6 on 2026-09-19 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_aiinstance'),
        ('server', '0007_remove_storageallocation_ai_instance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInstanceBay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_bays', to='model.aiinstance')),
                ('bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_allocations', to='server.bay')),
            ],
        ),
    ]
