# Generated by Django 6.0.6 on 2026-09-19 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_aiinstancebay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinstance',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ai_instances', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aiinstance',
            name='status',
            field=models.CharField(choices=[('stopped', 'Stopped'), ('running', 'Running'), ('training', 'Training'), ('moving', 'Moving'), ('not_installed', 'Not Installed')], default='not_installed', max_length=20),
        ),
    ]
