# Generated by Django 6.0.6 on 2026-09-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_aiinstance_user_alter_aiinstance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiinstance',
            name='bay',
        ),
    ]
