# Generated by Django 6.0.6 on 2026-09-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_remove_aiinstance_bay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinstance',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
