# Generated by Django 6.0.6 on 2026-09-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_alter_aiinstance_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinstance',
            name='status',
            field=models.CharField(choices=[('stopped', 'Stopped'), ('running', 'Running'), ('training', 'Training'), ('moving', 'Moving'), ('not_installed', 'Not Installed'), ('installing', 'Installing')], default='not_installed', max_length=20),
        ),
    ]
