# Generated by Django 6.0.6 on 2026-09-29 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_alter_aiinstance_status'),
        ('server', '0007_remove_storageallocation_ai_instance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IaInstallationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ai_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_installation', to='model.aiinstance')),
                ('allocate_bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_installation', to='server.storageallocation')),
            ],
        ),
    ]
