# Generated by Django 6.0.6 on 2026-10-06 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_iainstallationtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IaInstallationTask',
        ),
    ]
