# Generated by Django 6.0.6 on 2026-07-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=False)),
                ('watts', models.CharField(choices=[('1KW', 'Very Low (1KW)'), ('2KW', 'Low (2KW)'), ('4KW', 'Medium (4KW)'), ('8KW', 'HIGH (8KW)'), ('16KW', 'HIGH (16KW)')], default='2KW', max_length=10)),
                ('last_time_active', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('bay', models.IntegerField()),
            ],
        ),
    ]
