# Generated by Django 6.0.6 on 2026-07-06 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bay',
            name='CPU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.cpu'),
        ),
        migrations.AddField(
            model_name='bay',
            name='GPU',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.gpu'),
        ),
        migrations.AddField(
            model_name='bay',
            name='RAM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.ram'),
        ),
        migrations.AddField(
            model_name='bay',
            name='SSD',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hardware.ssd'),
        ),
    ]
