# Generated by Django 6.0.6 on 2026-06-30 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datacenterhack',
            old_name='bays',
            new_name='bay',
        ),
    ]
