# Generated by Django 6.0.6 on 2026-07-13 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bay',
            name='cpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpu_bay', to='user.inventoryitem'),
        ),
        migrations.AddField(
            model_name='bay',
            name='gpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpu_bay', to='user.inventoryitem'),
        ),
        migrations.AddField(
            model_name='bay',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ram_bay', to='user.inventoryitem'),
        ),
        migrations.AddField(
            model_name='bay',
            name='ssd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ssd_bay', to='user.inventoryitem'),
        ),
        migrations.AddField(
            model_name='rack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bay',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bays', to='server.rack'),
        ),
    ]
