# Generated by Django 6.0.6 on 2026-07-11 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bay',
            old_name='CPU',
            new_name='cpu',
        ),
        migrations.RenameField(
            model_name='bay',
            old_name='GPU',
            new_name='gpu',
        ),
        migrations.RenameField(
            model_name='bay',
            old_name='RAM',
            new_name='rem',
        ),
        migrations.RenameField(
            model_name='bay',
            old_name='SSD',
            new_name='ssd',
        ),
    ]
