# Generated by Django 6.0.6 on 2026-08-23 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_initial'),
        ('user', '0006_rename_actual_energy_user_actual_energy_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bay',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='bay',
            name='ram',
        ),
        migrations.AddField(
            model_name='bay',
            name='gpu1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpu_bay1', to='user.inventoryitem'),
        ),
        migrations.AddField(
            model_name='bay',
            name='gpu2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpu_bay2', to='user.inventoryitem'),
        ),
        migrations.AddField(
            model_name='bay',
            name='gpu3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpu_bay3', to='user.inventoryitem'),
        ),
        migrations.AddField(
            model_name='bay',
            name='ram1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ram_bay1', to='user.inventoryitem'),
        ),
        migrations.AddField(
            model_name='bay',
            name='ram2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ram_bay2', to='user.inventoryitem'),
        ),
        migrations.AddField(
            model_name='bay',
            name='ram3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ram_bay3', to='user.inventoryitem'),
        ),
    ]
