# Generated by Django 6.0.6 on 2026-07-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bay',
            name='last_time_active',
            field=models.DateTimeField(null=True),
        ),
    ]
