# Generated by Django 6.0.6 on 2026-07-11 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_rename_cpu_bay_cpu_rename_gpu_bay_gpu_and_more'),
        ('user', '0002_inventoryitem_is_equiped_inventoryitem_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bay',
            name='rem',
        ),
        migrations.AddField(
            model_name='bay',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ram_bay', to='user.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='bay',
            name='cpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpu_bay', to='user.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='bay',
            name='gpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpu_bay', to='user.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='bay',
            name='ssd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ssd_bay', to='user.inventoryitem'),
        ),
    ]
