# Generated by Django 6.0.6 on 2026-08-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_remove_bay_gpu_remove_bay_ram_bay_gpu1_bay_gpu2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bay',
            name='watts',
        ),
    ]
