# Generated by Django 6.0.6 on 2026-06-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0003_datacenterhack_name_bay'),
    ]

    operations = [
        migrations.AddField(
            model_name='bay',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
