# Generated by Django 6.0.6 on 2026-09-14 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_aiinstance'),
        ('server', '0005_alter_bay_cpu_alter_bay_gpu1_alter_bay_gpu2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_gb', models.BigIntegerField()),
                ('ai_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_allocations', to='model.aiinstance')),
                ('bay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_allocations', to='server.bay')),
            ],
        ),
    ]
