# Generated by Django 6.0.6 on 2026-09-14 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_aiinstance'),
        ('server', '0006_storageallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storageallocation',
            name='ai_instance',
        ),
        migrations.AddField(
            model_name='storageallocation',
            name='ai_model',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='storage_allocations', to='model.aimodel'),
            preserve_default=False,
        ),
    ]
