# Generated by Django 6.0.6 on 2026-07-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='actual_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65),
        ),
    ]
