# Generated by Django 6.0.6 on 2026-07-17 23:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_actual_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_refresh_balance',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
