# Generated by Django 6.0.6 on 2026-07-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_last_refresh_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='energy',
            field=models.PositiveIntegerField(default=23),
            preserve_default=False,
        ),
    ]
