# Generated by Django 6.0.6 on 2026-07-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='actual_energy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=65),
        ),
    ]
