# Generated by Django 6.0.6 on 2026-07-25 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_actual_energy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='actual_energy',
            new_name='actual_energy_rate',
        ),
    ]
