# Generated by Django 6.0.6 on 2026-08-26 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_actual_energy_user_actual_energy_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='Inventory',
            new_name='inventory',
        ),
    ]
