# Generated by Django 6.0.6 on 2026-08-26 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_inventory_inventoryitem_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='quantity',
        ),
    ]
