# Generated by Django 6.0.6 on 2026-09-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_inventoryitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='energy',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
