# Generated by Django 6.0.6 on 2026-09-07 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_remove_aimodel_serie'),
        ('user', '0009_alter_user_energy'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryIaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ia_models', to='user.inventory')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.aimodel')),
            ],
        ),
    ]
