# Generated by Django 6.0.6 on 2026-09-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_inventoryiamodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryiamodel',
            name='is_running',
        ),
        migrations.AddField(
            model_name='inventoryiamodel',
            name='status',
            field=models.CharField(choices=[('stopped', 'Stopped'), ('running', 'Running'), ('training', 'Training'), ('moving', 'Moving')], default='stopped', max_length=20),
        ),
    ]
