# Generated by Django 6.0.6 on 2026-09-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_inventoryiamodel_is_running_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryiamodel',
            name='status',
            field=models.CharField(choices=[('stopped', 'Stopped'), ('running', 'Running'), ('training', 'Training'), ('moving', 'Moving'), ('not_installed', 'Not Installed')], default='stopped', max_length=20),
        ),
    ]
